name = "sistema-estoque-24h"
main = "src/worker.mjs"
compatibility_date = "2026-04-05"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "estoque.24hlocacoes.com"
zone_name = "24hlocacoes.com"
custom_domain = true

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "sistema-estoque-24h"
database_id = "6b412f11-d7ca-4ae0-a485-7f1c6e063c9d"
migrations_dir = "./migrations"
